CREATE TABLE [T_Test] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Company] VARCHAR (50),
  [Last_Name] VARCHAR (50),
  [First_Name] VARCHAR (50),
  [E-mail_Address] VARCHAR (50),
  [Job_Title] VARCHAR (50),
  [Business_Phone] VARCHAR (25),
  [Home_Phone] VARCHAR (25),
  [Mobile_Phone] VARCHAR (25),
  [Fax_Number] VARCHAR (25),
  [Address] LONGTEXT ,
  [City] VARCHAR (50),
  [State/Province] VARCHAR (50),
  [ZIP/Postal_Code] VARCHAR (15),
  [Country/Region] VARCHAR (50),
  [Web_Page] LONGTEXT ,
  [Notes] LONGTEXT ,
  [Attachments] VARCHAR 
)
